### ISSUE TITLE
feat: add charge to the textual name

### ISSUE THREAD

**Issue by mmikhasenko** [JuliaPhysics/Corpuscles.jl#32]
It is convenient to get particles by their string name rather then id
it would be nice to store the charge in the text identified.

For example:
I would like to call `Sigma(c)(2455)+`, `Sigma(c)(2455)++`, or `Sigma(c)(2455)0`.
Now, all of them are `"Sigma(c)"` in the list
```
filter(p->occursin(r"Sigma\(c*\)", p.name), particles())
```

![image](https://user-images.githubusercontent.com/22725744/165096832-dd323161-0cc6-41d4-be5c-50d311e839ed.png)

**Comment by tamasgal** [comment]
Ah, @jstrube actually made a similar request #24 and also a PR #28. It does not use the `.name` field directly, but the actual row in the CSV, so we can implement this without breaking it, but the logic is not so simple.

See this function in `particle` which is also needed due to the fact that the charge is sometimes already encoded in the name:

https://github.com/scikit-hep/particle/blob/ca73302d3ebae1a9b3efdc26280e6f9f44301824/src/particle/particle/particle.py#L856-L903
